name: github-release
version: 1.0.5

category: Utility
description: GitHub Release uploads files to GitHub releases.
github: tfausak/github-release
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Upload files to GitHub releases.

dependencies:
  - base >= 4.8.2 && < 4.11
ghc-options:
  - -Wall

library:
  dependencies:
    - aeson >= 0.9 && < 1.3
    - bytestring >= 0.10.6 && < 0.11
    - http-client >= 0.4.30 && < 0.6
    - http-client-tls >= 0.2.4 && < 0.4
    - http-types >= 0.9 && < 0.10
    - mime-types >= 0.1 && < 0.2
    - optparse-generic >= 1.1 && < 1.3
    - text >= 1.2.2 && < 1.3
    - unordered-containers >= 0.2.5 && < 0.3
    - uri-templater >= 0.2 && < 0.4
  other-modules: Paths_github_release
  source-dirs: library

executables:
  github-release:
    dependencies:
      - github-release
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: github-release.hs
    source-dirs: executables
