category: Utility
description: GitHub Release is a command-line utility for uploading files to GitHub
  releases.
executables:
  github-release:
    dependencies:
    - base
    - github-release
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: source/executable
extra-source-files:
- CHANGELOG.markdown
- package.yaml
- README.markdown
- stack.yaml
ghc-options: -Wall
github: tfausak/github-release
library:
  dependencies:
  - aeson >=0.9 && <1.3
  - base >=4.8.2 && <4.10
  - bytestring >=0.10.6 && <0.11
  - http-client >=0.4.30 && <0.6
  - http-client-tls >=0.2.4 && <0.4
  - http-types >=0.9 && <0.10
  - mime-types >=0.1 && <0.2
  - optparse-generic >=1.1 && <1.3
  - text >=1.2.2 && <1.3
  - unordered-containers >=0.2.5 && <0.3
  - uri-templater >=0.2 && <0.3
  other-modules: Paths_github_release
  source-dirs: source/library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: github-release
synopsis: Upload files to GitHub releases.
version: '1.0.3'
